### ISSUE TITLE
DNN 9.02 Install errors

### ISSUE THREAD

**Issue by RobHuseman** [ChrisHammond/HammerFlex#26]
Issue 1.  Duplicate folder underneath zip folder.

Issue 2.  As per below install log.

An unknown error has occured. Please check your installation zip file and try again. 
 Common issues with bad installation files: •Zip file size is too large, check your IIS settings for max upload file size.
•Missing resources in the zip file.
•Invalid files in the package.
•File extension is not .zip.
•Check that you are logged in.

**Comment by ChrisHammond** [comment]
You uploaded the INSTALL Zip file for the skin?

**Comment by RobHuseman** [comment]
Hi Chris,

                Thanks for getting back to us.  Not sure how to respond, so will fill in facts.

1).  This is a new install of DNN which was implemented with 9.01 and then upgraded to 9.02.  The problem existed in both versions.

2).  If we download via the extensions menu for uninstalled products, the installation works fine.  It downloads, parses and then goes into the normal install menu.

3).  The C:\Websites\Root is the actual DNN directory, so assuming that you are referencing the “temp” as the anomaly.  I assume this is the working directory for the “Parsing”, and would further assume that somehow it is looking for a file which has not been included or created?

4).  The problem that there is a child directory of the same name when we view your zip files that we download does appear to be a problem.  When we “Extract” your files and then re-zip them without the child directory of the same name, we then get further in the installation and encounter the errors we sent you.  That was created with our version of the modified file.  When we do not modify the file, we get to 95% of the upload and then it fails with the standard errors.  Could that be an error in the uploaded version of your file?

5).  The same problem exist in other downloads including DNNContra files… so thinking the problem is either a bug or a new parameter/requirement for the files which has not been picked up on yet.

6).  As stated above, this is a brand new install and nothing has been published or modified.  Every other function and feature is working properly that we know of.  Again, the downloads from within the Extensions area also work fine, so only third party extensions that are downloaded and installed via the “Install Extensions” function are apparently affected.

7).  Environment is a Windows 2008 server with IIS 7.5.  It is a production box and currently host about a dozen websites of varying types.  Other ASP functions contained in some of those sites work properly.

8).  We have verified and played with varying “Permissions” for the folder structure and have made sure that “Full Control” is on all Folders/Sub-Folders for the DNN Super user.  We have also added and tested with the IIS User being granted same.

9).  We have also increased the maximum upload size for both the server and site.

10).  We have scoured for any way to better log or debug this process, but as “newbies”… have not yet figured out how to do that.

                Thanks for any help or suggestions you can offer…



Rob
Robert D. Huseman
President/CEO
Advanced Service Solutions, Inc.
5535 Bermuda Dunes Circle
Lake Worth, FL. 33463-6571

+1 (561) 432-1404 Voice
+1 (561) 432-1789 Fax

www.advancedservicesolutions.com<http://www.advancedservicesolutions.com/>
robert.huseman@assinet.com<mailto:robert.huseman@assinet.com>
[RDH-ASSIBusinessCardv02]
This message contains confidential information and is intended only for the individual(s) named.  If you are not a named addressee, you should not use, disseminate, distribute or copy this email.  If you have received this message in error please notify the sender by email immediately and delete this email from your system.  Email messages can be intercepted, corrupted, lost or contain viruses.  The sender does not accept liability for any errors or omissions in the contents of this message which arise during email transmission.
Think before you print. [Description: Think before you print.]  Think before you print.

**Comment by RobHuseman** [comment]
Hi Chris, this is the error in the log from the failure.  It seems to be a file or path not found error.

Log Name:      Application
Source:        ASP.NET 4.0.30319.0
Date:          3/31/2017 1:28:11 PM
Event ID:      1309
Task Category: Web Event
Level:         Warning
Keywords:      Classic
User:          N/A
Computer:      ASSI-DMZ-DNS-01
Description:
Event code: 3005 Event message: An unhandled exception has occurred. Event time: 3/31/2017 1:28:11 PM Event time (UTC): 3/31/2017 5:28:11 PM Event ID: 96a93294466c4dfdb6fb69c98eec38c1 Event sequence: 28 Event occurrence: 1 Event detail code: 0  Application information:     Application domain: /LM/W3SVC/6/ROOT-1-131354545848989622     Trust level: Full     Application Virtual Path: /     Application Path: C:\Websites\Root\     Machine name: ASSI-DMZ-DNS-01  Process information:     Process ID: 2452     Process name: w3wp.exe     Account name: IIS APPPOOL\dotnetnuke  Exception information:     Exception type: PathNotFoundException     Exception message: The system cannot find the file specified.
   at SchwabenCode.QuickIO.Internal.InternalQuickIOCommon.NativeExceptionMapping(String path, Int32 errorCode)
   at SchwabenCode.QuickIO.QuickIOFile.OpenFileStream(QuickIOPathInfo pathInfo, FileAccess fileAccess, FileMode fileOption, FileShare shareMode, Int32 buffer)
   at SchwabenCode.QuickIO.QuickIOFile.OpenText(QuickIOPathInfo pathInfo)
   at DotNetNuke.Common.Utilities.FileSystemUtils.ReadFile(String filePath)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadTextFromFile(String source)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadManifest(XPathNavigator manifestNav)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller..ctor(String packageManifest, InstallerInfo info)
   at DotNetNuke.Services.Installer.Installer.ProcessPackages(XPathNavigator rootNav)
   at DotNetNuke.Services.Installer.Installer.ReadManifest(Boolean deleteTemp)
   at Dnn.PersonaBar.Extensions.Components.InstallController.GetInstaller(Stream stream, String fileName, Int32 portalId, String legacySkin)
   at Dnn.PersonaBar.Extensions.Components.InstallController.ParsePackage(PortalSettings portalSettings, UserInfo user, String filePath, Stream stream)
   at Dnn.PersonaBar.Extensions.Services.ExtensionsController.<>c__DisplayClass36_1.<UploadFileAction>b__1(Object <state>)
   at System.Web.Util.SynchronizationHelper.SafeWrapCallback(Action action)

  Request information:     Request URL: http://dnncms.assinet.com/API/PersonaBar/Extensions/ParsePackage     Request path: /API/PersonaBar/Extensions/ParsePackage     User host address: 50.138.50.186     User: ASSIAdmin     Is authenticated: True     Authentication Type: Forms     Thread account name: IIS APPPOOL\dotnetnuke  Thread information:     Thread ID: 26     Thread account name: IIS APPPOOL\dotnetnuke     Is impersonating: False     Stack trace:    at SchwabenCode.QuickIO.Internal.InternalQuickIOCommon.NativeExceptionMapping(String path, Int32 errorCode)
   at SchwabenCode.QuickIO.QuickIOFile.OpenFileStream(QuickIOPathInfo pathInfo, FileAccess fileAccess, FileMode fileOption, FileShare shareMode, Int32 buffer)
   at SchwabenCode.QuickIO.QuickIOFile.OpenText(QuickIOPathInfo pathInfo)
   at DotNetNuke.Common.Utilities.FileSystemUtils.ReadFile(String filePath)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadTextFromFile(String source)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadManifest(XPathNavigator manifestNav)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller..ctor(String packageManifest, InstallerInfo info)
   at DotNetNuke.Services.Installer.Installer.ProcessPackages(XPathNavigator rootNav)
   at DotNetNuke.Services.Installer.Installer.ReadManifest(Boolean deleteTemp)
   at Dnn.PersonaBar.Extensions.Components.InstallController.GetInstaller(Stream stream, String fileName, Int32 portalId, String legacySkin)
   at Dnn.PersonaBar.Extensions.Components.InstallController.ParsePackage(PortalSettings portalSettings, UserInfo user, String filePath, Stream stream)
   at Dnn.PersonaBar.Extensions.Services.ExtensionsController.<>c__DisplayClass36_1.<UploadFileAction>b__1(Object <state>)
   at System.Web.Util.SynchronizationHelper.SafeWrapCallback(Action action)
  Custom event details:
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ASP.NET 4.0.30319.0" />
    <EventID Qualifiers="32768">1309</EventID>
    <Level>3</Level>
    <Task>3</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-03-31T17:28:11.000000000Z" />
    <EventRecordID>121908</EventRecordID>
    <Channel>Application</Channel>
    <Computer>ASSI-DMZ-DNS-01</Computer>
    <Security />
  </System>
  <EventData>
    <Data>3005</Data>
    <Data>An unhandled exception has occurred.</Data>
    <Data>3/31/2017 1:28:11 PM</Data>
    <Data>3/31/2017 5:28:11 PM</Data>
    <Data>96a93294466c4dfdb6fb69c98eec38c1</Data>
    <Data>28</Data>
    <Data>1</Data>
    <Data>0</Data>
    <Data>/LM/W3SVC/6/ROOT-1-131354545848989622</Data>
    <Data>Full</Data>
    <Data>/</Data>
    <Data>C:\Websites\Root\</Data>
    <Data>ASSI-DMZ-DNS-01</Data>
    <Data>
    </Data>
    <Data>2452</Data>
    <Data>w3wp.exe</Data>
    <Data>IIS APPPOOL\dotnetnuke</Data>
    <Data>PathNotFoundException</Data>
    <Data>The system cannot find the file specified.
   at SchwabenCode.QuickIO.Internal.InternalQuickIOCommon.NativeExceptionMapping(String path, Int32 errorCode)
   at SchwabenCode.QuickIO.QuickIOFile.OpenFileStream(QuickIOPathInfo pathInfo, FileAccess fileAccess, FileMode fileOption, FileShare shareMode, Int32 buffer)
   at SchwabenCode.QuickIO.QuickIOFile.OpenText(QuickIOPathInfo pathInfo)
   at DotNetNuke.Common.Utilities.FileSystemUtils.ReadFile(String filePath)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadTextFromFile(String source)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadManifest(XPathNavigator manifestNav)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller..ctor(String packageManifest, InstallerInfo info)
   at DotNetNuke.Services.Installer.Installer.ProcessPackages(XPathNavigator rootNav)
   at DotNetNuke.Services.Installer.Installer.ReadManifest(Boolean deleteTemp)
   at Dnn.PersonaBar.Extensions.Components.InstallController.GetInstaller(Stream stream, String fileName, Int32 portalId, String legacySkin)
   at Dnn.PersonaBar.Extensions.Components.InstallController.ParsePackage(PortalSettings portalSettings, UserInfo user, String filePath, Stream stream)
   at Dnn.PersonaBar.Extensions.Services.ExtensionsController.&lt;&gt;c__DisplayClass36_1.&lt;UploadFileAction&gt;b__1(Object &lt;state&gt;)
   at System.Web.Util.SynchronizationHelper.SafeWrapCallback(Action action)

</Data>
    <Data>http://dnncms.assinet.com/API/PersonaBar/Extensions/ParsePackage</Data>
    <Data>/API/PersonaBar/Extensions/ParsePackage</Data>
    <Data>50.138.50.186</Data>
    <Data>ASSIAdmin</Data>
    <Data>True</Data>
    <Data>Forms</Data>
    <Data>IIS APPPOOL\dotnetnuke</Data>
    <Data>26</Data>
    <Data>IIS APPPOOL\dotnetnuke</Data>
    <Data>False</Data>
    <Data>   at SchwabenCode.QuickIO.Internal.InternalQuickIOCommon.NativeExceptionMapping(String path, Int32 errorCode)
   at SchwabenCode.QuickIO.QuickIOFile.OpenFileStream(QuickIOPathInfo pathInfo, FileAccess fileAccess, FileMode fileOption, FileShare shareMode, Int32 buffer)
   at SchwabenCode.QuickIO.QuickIOFile.OpenText(QuickIOPathInfo pathInfo)
   at DotNetNuke.Common.Utilities.FileSystemUtils.ReadFile(String filePath)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadTextFromFile(String source)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller.ReadManifest(XPathNavigator manifestNav)
   at DotNetNuke.Services.Installer.Installers.PackageInstaller..ctor(String packageManifest, InstallerInfo info)
   at DotNetNuke.Services.Installer.Installer.ProcessPackages(XPathNavigator rootNav)
   at DotNetNuke.Services.Installer.Installer.ReadManifest(Boolean deleteTemp)
   at Dnn.PersonaBar.Extensions.Components.InstallController.GetInstaller(Stream stream, String fileName, Int32 portalId, String legacySkin)
   at Dnn.PersonaBar.Extensions.Components.InstallController.ParsePackage(PortalSettings portalSettings, UserInfo user, String filePath, Stream stream)
   at Dnn.PersonaBar.Extensions.Services.ExtensionsController.&lt;&gt;c__DisplayClass36_1.&lt;UploadFileAction&gt;b__1(Object &lt;state&gt;)
   at System.Web.Util.SynchronizationHelper.SafeWrapCallback(Action action)
</Data>
  </EventData>
</Event>

**Comment by ChrisHammond** [comment]
Closing due to age
